install: 
  - git clone https://github.com/PowerShell/DscResource.Tests
  - ps: |
      &nuget.exe install PoshBuildTools -source https://ci.appveyor.com/nuget/PoshBuildTools -outputDirectory "$env:USERPROFILE\Documents\WindowsPowerShell\Modules\" -ExcludeVersion
      Import-Module PoshBuildTools
      $moduleInfoList = New-BuildModuleInfo -Auto
      Write-verboseBuildModuleInfo -moduleInfoList $moduleInfoList
      Invoke-AppveyorInstall 


build_script:
  - ps: |
      Invoke-AppveyorBuild -moduleInfoList $moduleInfoList      

test_script:
  - ps: |
      Invoke-AppveyorTest -moduleInfoList $moduleInfoList 

on_finish:
  - ps: |
      Invoke-AppveyorFinish -moduleInfoList $moduleInfoList

cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache
